---
control:
  hosts:
    k8smaster:
      ansible_connection: local

centos:
  hosts:
    centos1:
    centos2:
    centos3:
  vars:
    ansible_user: root

ubuntus:
  hosts:
    ubuntu1:
    ubuntu2:
    ubuntu3:
    ubuntu:
  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_become_pass: password

linux:
  children:
    centos:
    ubuntus:
...

